# main.yml

# Workflow's name

name: Build Electron App For Win/Mac

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15, ubuntu-18.04]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      - name: Install pnpm
        run: npm install pnpm -g

      - name: pnpm install
        run: pnpm install

      - name: build windows app
        if: matrix.os == 'windows-2019'
        run: pnpm build:win

      - name: build mac app
        if: matrix.os == 'macos-10.15'
        run: pnpm run build:mac

      - name: build Ubuntu app
        if: matrix.os == 'ubuntu-18.04'
        run: pnpm run build:linux

      - name: cleanup artifacts for windows
        if: matrix.os == 'windows-2019'
        run: |
          mkdir artifacts
          mv dist/*.exe artifacts || true

      - name: cleanup artifacts for macosZ
        if: matrix.os == 'macos-10.15'
        run: |
          mkdir artifacts
          mv dist/*.dmg artifacts || true

      - name: cleanup artifacts for Ubuntu
        if: matrix.os == 'ubuntu-18.04'
        run: |
          mkdir artifacts
          mv dist/*.snap artifacts || true
          mv dist/*.AppImage artifacts || true

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: artifacts

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'artifacts/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
