name: 编译 Electron 应用

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: 编译 Electron 应用
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1

      - name: 安装 Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: Windows 编译
        if: matrix.os == 'windows-latest'
        run: pnpm build:win

      - name: Mac 编译
        if: matrix.os == 'macos-latest'
        run: pnpm run build:mac

      - name: Linux 编译
        if: matrix.os == 'ubuntu-latest'
        run: pnpm run build:linux

      - name: 创建目录
        run: mkdir artifacts

      - name: 清理 Windows
        if: matrix.os == 'windows-latest'
        run: mv dist/*.exe artifacts || true

      - name: 清理 Macos
        if: matrix.os == 'macos-latest'
        run: mv dist/*.dmg artifacts || true

      - name: 清理 Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/*.snap artifacts || true
          mv dist/*.AppImage artifacts || true

      - name: 上传文件
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: artifacts

      - name: 发布内容
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'artifacts/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
